// Data structure for air pollutants and their corresponding categories
export const airPollutants = [
  {
    ParameterCode: "OZONE",
    label: "O3",
    ParameterDescription: "Ozone",
    Units: "pphm",
    categories: [
      { label: "No data", range: "N/A" },
      { label: "Good", range: "< 5.4" },
      { label: "Fair", range: "5.4 - 8.0" },
      { label: "Poor", range: "8.0 - 12.0" },
      { label: "Very poor", range: "12.0 - 16.0" },
      { label: "Extremely poor", range: "> 16.0" },
    ],
  },
  {
    ParameterCode: "PM2.5",
    label: "PM2.5",
    ParameterDescription: "PM 2.5",
    Units: "µg/m³",
    categories: [
      { label: "No data", range: "N/A" },
      { label: "Good", range: "< 25" },
      { label: "Fair", range: "25 - 50" },
      { label: "Poor", range: "50 - 100" },
      { label: "Very poor", range: "100 - 300" },
      { label: "Extremely poor", range: "> 300" },
    ],
  },{
    ParameterCode: "PM10",
    label: "PM10",
    ParameterDescription: "PM 10",
    Units: "µg/m³",
    categories: [
      { label: "Good", range: "< 50" },
      { label: "Fair", range: "50 - 100" },
      { label: "Poor", range: "100 - 200" },
      { label: "Very poor", range: "200 - 600" },
      { label: "Extremely poor", range: "> 600" },
    ],
  },
  {
    ParameterCode: "AQC",
    ParameterDescription: "AQC",
    Units: "Category",
    UnitsDescription: "category",
    Category: "Site AQC",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  // {
  //   ParameterCode: "NO2",
  //   ParameterDescription: "NO2",
  //   Units: "pphm",
  //   categories: [
  //     { label: "Good", range: "< 25" },
  //     { label: "Fair", range: "25 - 50" },
  //     { label: "Poor", range: "50 - 100" },
  //     { label: "Very poor", range: "100 - 300" },
  //     { label: "Extremely poor", range: "> 300" },
  //   ],
  // },
  // {
  //   ParameterCode: "WDR",
  //   ParameterDescription: "Wind direction",
  //   Units: "°",
  //   categories: [
  //     { label: "Good", range: "< 25" },
  //     { label: "Fair", range: "25 - 50" },
  //     { label: "Poor", range: "50 - 100" },
  //     { label: "Very poor", range: "100 - 300" },
  //     { label: "Extremely poor", range: "> 300" },
  //   ],
  // },
  // {
  //   ParameterCode: "WSP",
  //   ParameterDescription: "Wind speed",
  //   Units: "m/s",
  //   categories: [
  //     { label: "Good", range: "< 25" },
  //     { label: "Fair", range: "25 - 50" },
  //     { label: "Poor", range: "50 - 100" },
  //     { label: "Very poor", range: "100 - 300" },
  //     { label: "Extremely poor", range: "> 300" },
  //   ],
  // },
];

/*
const airPollutants = [
  {
    ParameterCode: "AQC",
    ParameterDescription: "AQC",
    Units: "category",
    UnitsDescription: "category",
    Category: "Site AQC",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "AQC",
    ParameterDescription: "AQC",
    Units: "category",
    UnitsDescription: "category",
    Category: "Site AQC",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "8h rolling average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "8h rolling average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "8h rolling average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "8h rolling average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "8h rolling average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "8h rolling average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "8h rolling average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "8h rolling average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Maximums",
    SubCategory: "Daily",
    Frequency: "8h rolling average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "8h rolling average derived from 1h average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Maximums",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "CO",
    ParameterDescription: "Carbon monoxide",
    Units: "ppm",
    UnitsDescription: "parts per million",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "HUMID",
    ParameterDescription: "Humidity",
    Units: "%",
    UnitsDescription: "percent",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NEPH",
    ParameterDescription: "Nephelometer ",
    Units: "10^-4 m^-1",
    UnitsDescription: "10^-4 m^-1",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "NEPH",
    ParameterDescription: "Nephelometer ",
    Units: "10^-4 m^-1",
    UnitsDescription: "10^-4 m^-1",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NEPH",
    ParameterDescription: "Nephelometer ",
    Units: "10^-4 m^-1",
    UnitsDescription: "10^-4 m^-1",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NEPH",
    ParameterDescription: "Nephelometer ",
    Units: "10^-4 m^-1",
    UnitsDescription: "10^-4 m^-1",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NEPH",
    ParameterDescription: "Nephelometer ",
    Units: "10^-4 m^-1",
    UnitsDescription: "10^-4 m^-1",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NEPH",
    ParameterDescription: "Nephelometer ",
    Units: "10^-4 m^-1",
    UnitsDescription: "10^-4 m^-1",
    Category: "Maximums",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NEPH",
    ParameterDescription: "Nephelometer ",
    Units: "10^-4 m^-1",
    UnitsDescription: "10^-4 m^-1",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NEPH",
    ParameterDescription: "Nephelometer ",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NEPH",
    ParameterDescription: "Nephelometer ",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NEPH",
    ParameterDescription: "Nephelometer ",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NH3",
    ParameterDescription: "Ammonia",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "NH3",
    ParameterDescription: "Ammonia",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NH3",
    ParameterDescription: "Ammonia",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NH3",
    ParameterDescription: "Ammonia",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NH3",
    ParameterDescription: "Ammonia",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NH3",
    ParameterDescription: "Ammonia",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NH3",
    ParameterDescription: "Ammonia",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO",
    ParameterDescription: "Nitric Oxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "NO",
    ParameterDescription: "Nitric Oxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO",
    ParameterDescription: "Nitric Oxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO",
    ParameterDescription: "Nitric Oxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO",
    ParameterDescription: "Nitric Oxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO",
    ParameterDescription: "Nitric Oxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Yearly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "NO2",
    ParameterDescription: "Nitrogen Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "4h rolling average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "4h rolling average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "4h rolling average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "4h rolling average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "4h rolling average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "4h rolling average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "4h rolling average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "4h rolling average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Daily",
    Frequency: "4h rolling average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "4h rolling average derived from 1h average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "OZONE",
    ParameterDescription: "Ozone",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "24h rolling average derived from 1h average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Maximums",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Yearly",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM10",
    ParameterDescription: "PM10",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM10d",
    ParameterDescription: "Particulate Matter (<10 µm) (Dustwatch)",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "24h rolling average derived from 1h average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Maximums",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Yearly",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "24h rolling average derived from 1h average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM2.5",
    ParameterDescription: "PM2.5",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "PM2.5d",
    ParameterDescription: "Particulate Matter (<2.5 µm) (Dustwatch)",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "RAIN",
    ParameterDescription: "Rainfall",
    Units: "mm/m²",
    UnitsDescription: "millimetre rainfall",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "RAQC",
    ParameterDescription: "RAQC",
    Units: "category",
    UnitsDescription: "category",
    Category: "Regional AQC",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "RAQC",
    ParameterDescription: "RAQC",
    Units: "category",
    UnitsDescription: "category",
    Category: "Regional AQC",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SD1",
    ParameterDescription: "Wind Direction Sigma Theta",
    Units: "°",
    UnitsDescription: "degree",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "count",
    UnitsDescription: "number of exceedances",
    Category: "Exceedences",
    SubCategory: "Yearly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Daily",
    Frequency: "24h average derived from 1h average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Averages",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Annual",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Daily",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SO2",
    ParameterDescription: "Sulphur Dioxide",
    Units: "pphm",
    UnitsDescription: "parts per hundred million",
    Category: "Maximums",
    SubCategory: "Monthly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "SOLAR",
    ParameterDescription: "Solar radiation",
    Units: "W/m²",
    UnitsDescription: "watt per square meter ",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "TEMP",
    ParameterDescription: "Temperature",
    Units: "°C",
    UnitsDescription: "degree Celsius",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "TSPd",
    ParameterDescription: "Total Suspended Particles (Dustwatch)",
    Units: "µg/m³",
    UnitsDescription: "microgram per cubic meter",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "WDR",
    ParameterDescription: "Wind Direction (10m) ",
    Units: "°",
    UnitsDescription: "degree",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
  {
    ParameterCode: "WSP",
    ParameterDescription: "Wind Speed (10m)  ",
    Units: "m/s",
    UnitsDescription: "meter per second",
    Category: "Averages",
    SubCategory: "Hourly",
    Frequency: "Hourly average",
  },
];

export default airPollutants;

*/